version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./nginx/site/:/usr/share/nginx/html/
      - ./nginx/log/:/var/log/nginx/
    depends_on:
      - php
    networks:
      - lemp-network-test
      
  php:
    image: rendyuwu/php:7.4-fpm
    container_name: php
    expose: 
      - "9000"
    volumes:
      - ./php/:/usr/local/etc/php/
      - ./nginx/site/:/usr/share/nginx/html/
    networks:
      - lemp-network-test

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes: 
      - ./mariadb/conf/:/etc/mysql/conf.d/
      - ./mariadb/log/:/var/log/mysql/
    environment: 
      MYSQL_ROOT_PASSWORD: root
    networks:
      - lemp-network-test

networks:
  lemp-network-test:
    driver: bridge
    ipam:
      driver: default
